### ISSUE TITLE
node warning - process.on(SIGPROF) is reserved while debugging

### ISSUE THREAD

**Issue by pmuellr** [nodesource/nscm#19] opened 2017-06-15 20:09 UTC
Got this while running `nscm` with no args from a tmp directory with node 8.1.2

```
$ nscm
(node:35868) Warning: process.on(SIGPROF) is reserved while debugging
ENOENT: no such file or directory, open 'package.json'
```

A colleague suggests that this is caused by a pre-req shutdown handler which is binding to all the signals, but SIGPROF is no longer bindable in 8.1.2 - or something.

**Comment by pmuellr** [comment] 2017-06-15 20:18
related issue in node - https://github.com/nodejs/node/issues/12706

**Comment by Fishrock123** [comment] 2017-06-15 20:31
This is caused by an old version of [`signal-exit`](https://www.npmjs.com/package/signal-exit).

Here is where it is in the dep tree:
```
├─┬ nscm@1.5.0
│ ├─┬ args@2.3.0
│ │ ├── camelcase@4.0.0
│ │ ├── chalk@1.1.3 deduped
│ │ ├─┬ loud-rejection@1.3.0
│ │ │ ├── array-find-index@1.0.2
│ │ │ └── signal-exit@2.1.2
```

We want `signal-exit` 3.0+.

**Comment by julianduque** [comment] 2017-09-18 14:56
This should be fixed now, dependency updated.

**Closed as completed by julianduque** 2017-09-18 14:56 UTC
